repos:
  - repo: https://github.com/ekorchmar/pre-commit-dprint
    rev: v0.47.2 # Use the sha / tag you want to point at
    hooks:
      - id: dprint
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua # or stylua-system / stylua-github
