repos:
  - repo: https://github.com/spinergie/pre-commit-dprint
    rev: ""
    hooks:
      - id: dprint
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua # or stylua-system / stylua-github
