repos:
  - repo: https://github.com/spinergie/pre-commit-dprint
    rev: "v0.52.0"
    hooks:
      - id: dprint
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.4.0
    hooks:
      - id: stylua # or stylua-system / stylua-github

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.6
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
