"$schema" = 'https://starship.rs/config-schema.json'

format = """
$cmd_duration\
$status[$os $username$hostname $shell$shlvl](bg:153 fg:235)\
$directory\
$git_branch\
$git_commit\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$rlang\
$lua\
$java\
$c\
$julia\
$time$battery\
\n$character"""

# Directory and git
[directory]
truncate_to_repo = false
style = "fg:239 bg:111"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = "git"
style = "fg:111 bg:239"
format = '[ $symbol $branch ]($style)'

[git_commit]
tag_symbol = "tag"
style = "fg:111 bg:239"
format = '[ $hash$tag ]($style)'

[git_status]
style = "fg:111 bg:239"
format = '[($all_status$ahead_behind )]($style)'

# Languages
[nodejs]
symbol = "js"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'

[rust]
symbol = "rs"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'

[golang]
symbol = "go"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'

[php]
symbol = "php"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'

[python]
symbol = "py"
style = "bg:236"
format = '[[ $symbol ($virtualenv $version) ](fg:111 bg:236)]($style)'

[rlang]
symbol = "R"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'

[lua]
symbol = "lua"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'

[java]
symbol = "jav"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'
detect_files = ['pom.xml', 'build.gradle.kts', 'build.sbt', '.java-version', 'deps.edn', 'project.clj', 'build.boot', '.sdkmanrc', 'build.xml']

[c]
symbol = "c"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'
detect_extensions = ['c', 'h', 'cpp', 'hpp']

[julia]
symbol = "jl"
style = "bg:236"
format = '[[ $symbol ($version) ](fg:111 bg:236)]($style)'

# Standart prompt elements
[username]
show_always=true
style_user="bg:153 fg:235 bold"
style_root="bg:153 fg:167 bold"
format = '[$user]($style)'

[hostname]
ssh_only=false
ssh_symbol=""
style="bg:153 fg:235"
format="@[$ssh_symbol$hostname]($style)"

[os]
format = '[ $symbol ]($style)'
style="bg:153 fg:235"
disabled=true

[os.symbols]
Windows = "windows"
Linux = "linux"
Ubuntu = "ubuntu"
Macos = "macos"
Arch = "arch"

[shell]
disabled=true
style="bg:153 fg:235"
bash_indicator="bash"
zsh_indicator="zsh"
powershell_indicator="pwsh"
fish_indicator="fish"
cmd_indicator="cmd"

[shlvl]
disabled=false
style="bg:153 fg:235"
format='[/$shlvl]($style)'

[character]
format=" $symbol[: ](bold white)"
success_symbol='[\$ ](bold 212)'
error_symbol='[\$ ](bold 167)'
vimcmd_symbol="[N ](bold 140)"
vimcmd_replace_one_symbol="[R1](bold 179)"
vimcmd_replace_symbol="[R ](bold 179)"
vimcmd_visual_symbol="[V ](bold 149)"

[status]
disabled=true
map_symbol=true
format="[$signal_name$common_meaning]($style)\n"
style="bold white bg:red"

[cmd_duration]
disabled = true
format = "[ done in $duration]($style)\n"
show_milliseconds = true
min_time = 5_000

# Physical world
[battery]
format = '[$percentage]($style)'

[[battery.display]]
threshold = 10
style="bg:235 fg:167"

[[battery.display]]
threshold = 30
style="bg:235 fg:179"

[[battery.display]]
threshold = 55
style="bg:235 fg:80"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:235"
format = '[[ $time ](fg:80 bg:235)]($style)'

